= Verwendung von Asciidoctor unter Windows und macOS
:source-highlighter: rouge
:icons: font
:lang: DE
:hyphens:
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:folder: :file_folder:
:file-code-o: :page_facing_up:
endif::[]

*link:https://raw.githubusercontent.com/Die-Spengergasse/course-pos-csharp_basics/refs/heads/master/07%20Asciidoctor/asciidoc_quick_reference.svg[Zum cheat sheet]*

Mit Asciidoctor kannst du technische Dokumentationen in einem einfachen Textformat schreiben.
Die Struktur ähnelt Markdown. Asciidoctor bietet jedoch mehr Funktionen.
Das Tool liefert keine eigenständige Windows-Datei aus.
Ein *Docker-Image* ermöglicht jedoch eine einfache Installation auch unter Windows.

[IMPORTANT]
Für die nachfolgenden Schritte brauchst du eine lauffähige Installation von Docker.

== Installation der Extensions für VS Code

Diese Extensions erleichtern dir die Arbeit mit AsciiDoc-Dateien in Visual Studio Code.
Installiere folgende Erweiterungen:

- link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[Asciidoctor]
- link:https://marketplace.visualstudio.com/items?itemName=schletz.asciidoc-productivity[asciidoc-productivity]

Wir beschreiben die Extension _asciidoc-productivity_ link:04_adoc_productivity.adoc[→ in diesem Kapitel] ausführlich.

== Browser-Extension für AsciiDoc

Um deine Dokumente direkt im Browser anzuzeigen, installiere die Extension **Asciidoctor.js Live Preview**.
Du findest sie unter https://docs.asciidoctor.org/browser-extension/install/.
Sie unterstützt mehr Funktionen und zeigt deine Inhalte daher genauer an als die integrierte Vorschau von VS Code.

[NOTE]
Um lokale Dateien anzuzeigen, musst du der Erweiterung in den Einstellungen das Recht *Zugriff auf Datei-URLs zulassen* erteilen.

== Command-Line-Tool für die Konvertierung (optional)

Ein Command-Line-Tool wandelt deine Dokumente ebenfalls in PDF um.
Du kannst dieses Tool auch über das Kontextmenü der Extension *asciidoc-productivity* nutzen.
Für automatisierte Prozesse eignet sich das CLI-Tool besser:

=== Installation unter Windows

1. Lade die Datei link:convert_adoc.cmd[convert_adoc.cmd] herunter.
   Falls dein Browser eine Warnmeldung anzeigt, klicke auf *Trotzdem beibehalten*.
2. Erstelle den Ordner *C:\asciidoc* und verschiebe die Datei dorthin.
3. Starte die Datei durch einen Doppelklick.

Das Skript lädt beim ersten Start das Docker-Image *asciidoctor-pandoc* herunter.
Dieser Vorgang kann einige Minuten dauern.
Du musst ihn nur einmal ausführen.

=== Installation unter macOS

Erstelle einen neuen Ordner für das Skript (z. B. */Users/username/Scripts*) oder nutze einen bestehenden Ordner.
Öffne die Datei **link:convert_adoc.sh[convert_adoc.sh]** in VS Code und füge ihren Inhalt in einen neuen Editor-Tab ein.
Speichere die Datei unter *convert_adoc.sh* ab.
Wechsle im Terminal in diesen Ordner und führe folgende Befehle aus.
Sie geben dem Skript Ausführungsrechte und starten es einmalig, um das Docker-Image zu erstellen.

```bash
chmod a+x convert_adoc.sh
./convert_adoc.sh
```

=== Konvertieren von AsciiDoc-Dokumenten

Lade die folgenden Dateien herunter.
Sie enthalten ein Beispiel für ein AsciiDoc-Dokument.
Nutze in GitHub den *Download raw file*-Button.
GitHub zeigt das *adoc*-Dokument an, unterstützt jedoch nicht alle Funktionen.

- link:adoc%20demo.adoc[adoc demo.adoc]
- link:adoc%20demo.yml[adoc demo.yml]

Wechsle im Terminal in diesen Ordner (z. B. *Downloads*).
Führe den folgenden Befehl aus:

**Windows**
```
C:\asciidoc\convert_adoc "adoc demo.adoc" "adoc demo.pdf"
```

**macOS**
```
/Users/username/Scripts/convert_adoc.sh "adoc demo.adoc" "adoc demo.pdf"
```

Der Befehl erstellt nun eine PDF-Datei.
Das Tool erstellt jedoch nicht nur PDFs.
Du kannst die Ausgabe auch als md (Markdown), HTML oder docx (Word) speichern.
Je nach Endung wählt das Skript automatisch die richtigen Befehle.

```
C:\asciidoc\convert_adoc "adoc demo.adoc" "adoc demo.html"
C:\asciidoc\convert_adoc "adoc demo.adoc" "adoc demo.md"
C:\asciidoc\convert_adoc "adoc demo.adoc" "adoc demo.docx"
```

Markdown und Word unterstützen jedoch nicht alle Funktionen (z. B. automatische Zeilennummern oder Callouts).
Nutze daher immer die PDF- oder HTML-Ausgabe, wenn möglich.

[NOTE]
Du kannst `C:\asciidoc` in den Systemeinstellungen zur *PATH*-Variable hinzufügen. Dann musst du den Pfad nicht mehr manuell eingeben.

== Infos über die Musterdateien

Die Datei link:adoc%20demo.adoc[adoc demo.adoc] enthält den Text und die Formatierungsanweisungen.
Für Kopf- und Fußzeilen kannst du eine separate YAML-Datei nutzen.
Die Datei link:adoc%20demo.yml[adoc demo.yml] beschreibt beispielsweise den Stil der Fußzeile.
Das Skript *convert_adoc* erkennt automatisch ein passendes Layout, wenn eine YML-Datei mit dem gleichen Namen wie die adoc-Datei existiert.

== Cheat sheet

image::asciidoc_quick_reference.svg[]