= Kommentar

== Eingabetext

=== Westenthaler tobt wegen Haushaltsabgabe: "Amoklauf des ORF"

Wegen der Haushaltsabgabe tobt ein mächtiger Streit. Die FPÖ und ihr Stiftungsrat Peter Westenthaler sind sauer. 

Westenthaler spricht von einem "Amoklauf". Er will die Zuseher vertreten - und deren Interessen.

Westenthaler ortet ein "Chaos pur". Nichts funktioniere bei der Haushaltsabgabe, stellt Westenthaler fest. Die Zahlungsaufforderungen sind in Westenthalers Augen ein "Skandal".

Der FPÖ-Stiftungsrat will die Haushaltsabgabe kippen. Der ORF soll eine alternative Finanzierung für den Sender finden. "Der Kampf geht weiter", kündigte Westenthaler schon vor der Sitzung des Stiftungsrates an.

Auch die Personalausgaben im ORF, sprich die Gehälter, will Westenthaler deckeln. Er will Kürzungen und eine neue Gehaltspyramide. Westenthaler will "Privilegien-Gehälter" abschaffen und den "einfachen" Mitarbeitern dafür mehr Geld geben.

== Rhetorische Stilmittel

chatgpt_prompt::["Analysiere rhetorische Stilmittel zu folgendem Artikel:
https://www.oe24.at/oesterreich/politik/westenthaler-tobt-wegen-haushaltsabgabe-amoklauf-des-orf/613706268
",max_tokens=8192,temperature=0.5,resolve_links=true]

== Kommentar

chatgpt_prompt::["Schreibe einen Kommentar in 600 Worten zum Artikel zu folgendem Artikel:
https://www.oe24.at/oesterreich/politik/westenthaler-tobt-wegen-haushaltsabgabe-amoklauf-des-orf/613706268
Beachte folgenden Regeln:
https://www.deutsche-grammatik.net/textsorten-srdp/kommentar/
",max_tokens=8192,temperature=0.5,resolve_links=true]

