export const sourceTypes: Record<string, string> = {
    "cs": "[source,csharp]",
    "csproj": "[source,xml]",
    "java": "[source,java]",
    "rb": "[source,ruby]",
    "json": "[source,json]",
    "js": "[source,javascript]",
    "ts": "[source,typescript]",
    "jsx": "[source,jsx]",
    "tsx": "[source,tsx]",
    "py": "[source,python]",
    "txt": "[source]",
    "xml": "[source,xml]",
    "adoc": "[source,asciidoc]",
    "md": "[source,markdown]",
    "cmd": "[source]",
    "sh": "[source,bash]",
    "sql": "[source,sql]",
    "yaml": "[source,yaml]",
    "puml": "[source]",
};
